#!/bin/bash

# Countdown timer
 date1=$((`date +%s` + $1));
 while [ "$date1" -ne `date +%s` ]; do
   echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
 done
 terminal-notifier -title 'Countdown Timer' -message 'Times up!'

