#! /bin/bash

date=$(date +"%Y%m%d%H%M%S")
attribute=description
changet=modify
outputfile=batchfile$date.ldif
newvalue=RESET
numchanges=1000

echo "Deleting $outputfile if it exists"
rm -f $outputfile

for num in `seq $numchanges`
do
	echo "dn: uid=user.$num,ou=People,dc=example,dc=com" >> $outputfile
	echo "changetype: $changet" >> $outputfile
	echo "replace: $attribute" >> $outputfile
	echo "$attribute: $newvalue" >> $outputfile
	echo "" >> $outputfile
done
