#! /bin/bash

date=$(date +"%Y%m%d%H%M%S")
attribute=description
changet=add
outputfile=testentries$date.ldif

count=0
  if [[ $1 -gt $num_levels ]]
  then
    exit 0
  fi

  if[[ $1 -eq 0 ]]
  then
    echo "dn: uid=test.$1,ou=People,dc=example,dc=com" >> $outputfile
    echo "objectClass: top" >> $outputfile
    echo "objectClass: person" >> $outputfile
    echo "objectClass: organizationalPerson" >> $outputfile
    echo "objectClass: inetOrgPerson" >> $outputfile
    echo "sn: testentry.$1" >> $outputfile
    echo "cn: testentry.$1" >> $outputfile
    echo "uid: testentry.$1" >> $outputfile
    echo "mail: test" >> $outputfile
    echo "initials: test" >> $outputfile
    echo "homePhone: +1 111 111 111" >> $outputfile
    echo "pager: +1 111 111 111" >> $outputfile
    echo "givenName: test" >> $outputfile
    echo "employeeNumber: 1" >> $outputfile
    echo "telephoneNumber: +1 111 111 1111" >> $outputfile
    echo "mobile: +1 111 111 1111" >> $outputfile
    echo "userPassword: password" >> $outputfile
    echo "description: test" >> $outputfile
    echo "street: test" >> $outputfile
    echo "st: TX" >> $outputfile
    echo "l: Test" >> $outputfile
    echo "postalCode: 39160" >> $outputfile
    echo "postalAddress: test" >> $outputfile
    echo "" >> $outputfile
  fi
