#!/bin/bash

# Possible usage $ generateldifmodify --entries 100 --ldiffile myfile --type mail --type street --type basednalAddress

iterations=$1
counter=0
basedn=ou=People,dc=example,dc=com

stringlenmax=64
changetype=modify
type=replace
attributes=('mail' 'street' 'postalAddress')

randomstring()
{
  cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-$stringlenmax} | head -n 1
}

while [ $counter -lt $iterations ]
do
  echo "dn: uid=user.$counter,$basedn"
  echo "changetype: $changetype"

  for A in ${attributes[*]}
  do
    echo "$type: $A"
    result=$(randomstring)
    echo "$A: $result"
    echo "-"
  done

  ((counter++))

  echo ""
done
