#! /bin/bash

UTIL_DIR=~/versions/5.2.0.0/UnboundID-DS
SERVERS=('x3550-02' 'x3550-03' 'x3550-04')
PORTS=('2389' '3389')
BINDDN='cn=directory manager'
BINDPASSWORD="password"
BASEDN="ou=people,dc=example,dc=com"

for server in ${SERVERS[*]}
do
  for port in ${PORTS[*]}
  do
    echo ""
    echo "Seaching $server on port $port"
    $UTIL_DIR/bin/ldapsearch --hostname $server --port $port --binddn "$BINDDN" --bindpassword $BINDPASSWORD --baseDN $BASEDN "($1)"
  done
done
