#!/bin/bash
# This script only works with OSX
if [ "$(uname)" == "Darwin" ]; then
  sudo rm -rf /private/var/log/asl/*.asl
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  echo "" # Nothing here yet
fi
