#!/bin/bash

# add the list of machines that need to be upgraded
host_machines=('x3550-04' 'x3550-06' 'x3550-11')

# upgrade location information on the host machines
local_base=~/versions
host_base=/ds/alu-*
upload_base=/ds/server_upgrade

# some globals
ds_name=ds-
proxy_name=proxyserver

my_machine=$HOSTNAME

# get all the items found in products
for machine in ${host_machines[*]}
do
#  if [ !"ssh root@$machine test -wd "'$upload_base'"" ]; then
#      ssh root@$machine "mkdir '$upload_base'"
#  fi

  # delete old upgrade information
  ssh root@$machine 'rm -rf /ds/server_upgrade/*.zip; rm -rf /ds/server_upgrade/unboundid-*'

  # copy zip files to $machine
  scp -c blowfish $local_base/*.zip root@$machine:$upload_base

  # uncompress files to $machine

  ssh root@$machine 'cd /ds/server_upgrade; unzip -o directory*; unzip -o proxy*'

done

